### ISSUE TITLE
Colorization of output

### ISSUE THREAD

**Issue by schvabodka-man** [dmerejkowsky/pycp#16]
Are there any possibilities to add colorization to this tool? Everything is brilliant but absent of colorized stdout is real issue when copying/moving multiple files in bulk.

**Comment by dmerejkowsky** [comment]
> Everything is brilliant
Thanks !

Well, this may be a good opportunity to use [python-cli-ui](https://pypi.python.org/pypi/python-cli-ui/0.5.0).

Somehow I feel I can trust its author

**Comment by dmerejkowsky** [comment]
Ask and you shall receive.

The pull request is a bit hard to review, sorry (lots of refactorings), but if you wanna give it a try, you're welcome.

If you want to skip the review, feel free to do so :). I'll merge it and publish a new release "soonish"

Cheers :)

**Comment by schvabodka-man** [comment]
I know shit about Python so i can't "review" it properly, sorry.

**Comment by dmerejkowsky** [comment]
no problem :)

**Comment by dmerejkowsky** [comment]
You can still give your opinion about what the colored output look like:

![pycp-global-colors](https://user-images.githubusercontent.com/606755/32147475-2503f526-bce8-11e7-89aa-89245ed629ab.png)

**Comment by schvabodka-man** [comment]
Brown on dark background doesn't look very "eye friendly", but at all looks sweet

**Comment by dmerejkowsky** [comment]
Here you go:

![pycp-yellow](https://user-images.githubusercontent.com/606755/32176810-f0f4d1e6-bd88-11e7-8f16-39e0e3174fea.png)

**Comment by schvabodka-man** [comment]
That's a lot nicer

**Comment by dmerejkowsky** [comment]
Ok, the v.8 is out. But there are serious performance problems (sorry)

See #20 for the details.

May be best to wait for 8.1 ...
